### PR TITLE
loop queries to avoid overflow error

### PR DESCRIPTION
**Pull request by Philipp-Neubauer**
hopefully addresses #84 and #79

### CODE REVIEW

**Comment by sckott** [comment]
Thanks! However, seems like you forked off of an old commit and didn't update. Can you pull in latest from master here?  and then push up again to `Philipp-Neubauer:cherrpick`

same for other PR

**Comment by Philipp-Neubauer** [comment]
Should be ok for the other PR, no? I realised this might cause trouble half
way through and updated the other branch...or so I thought. Will check.

On Wed, Mar 23, 2016 at 11:39 AM, Scott Chamberlain <
notifications@github.com> wrote:

> Thanks! However, seems like you forked off of an old commit and didn't
> update. Can you pull in latest from master here? and then push up again to
> Philipp-Neubauer:cherrpick
>
> same for other PR
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rfishbase/pull/95#issuecomment-200064124>
>



-- 
Phil

**Comment by sckott** [comment]
woops, yep, your other PR is fine :)

**Comment by Philipp-Neubauer** [comment]
Ok, just pushed the merge, see if this works...got a bit confused by the forking-cherry-picking-merging-upstream-commits process, hopefully this did the trick.

**Comment by sckott** [comment]
great, thanks!

**Comment by sckott** [comment]
Hmm, did you test this code?  I get:

```r
load_taxa(update = TRUE)
#> Error in ifelse(server == SEALIFEBASE_API, limit = min(limit, 120000L),  : 
#>   unused arguments (limit = min(limit, 120000), limit = min(limit, 33000))
```

**Comment by Philipp-Neubauer** [comment]
D'oh! Not sure why that never threw errors when I ran it before (I actually use it as part of a project...). Fixed now, with amended test and updated doc.

**Comment by sckott** [comment]
great, thanks!

**Comment by sckott** [comment]
LGTM

**Pull request merged**
