### PR TITLE
add possibility to load entire table in single or looped API call from endpoint

### PR DESCRIPTION
**Pull request by Philipp-Neubauer**
Loop for the endpoint closure with offset since that was giving the same limit error with large species_lists as in #79. I also added a way to load the entire table at once instead of doing loops over each species in the endpoint closure (by omitting the species list in the fxn args), since the repeated API calls make the process very slow when the species list is large - at least for me. In that case, it seems much faster to query the entire table and subset it with the desired species codes afterward. I'm doing that outside of the function at the moment, but could be done within the function I suppose.

### CODE REVIEW

**Comment by Philipp-Neubauer** [comment]
PS have added a simple tweak to address #80: e.g. ```country(query = list(C_Code=440))``` now works.

**Comment by Philipp-Neubauer** [comment]
Also added functionality to ```endpoint``` to support sealifebase queries (```speccode``` was hardwired to fishbase it seemed). ```species("Cancer borealis", fields='DemersPelag', server=getOption("FISHBASE_API", SEALIFEBASE_API))``` now works.

**Comment by sckott** [comment]
> Also added functionality to endpoint to support sealifebase queries 

Where is this change?

**Comment by sckott** [comment]
> added a simple tweak to address #80:

which change is that?

**Comment by Philipp-Neubauer** [comment]
https://github.com/Philipp-Neubauer/rfishbase/blob/cherrypick/R/00-endpoint.R#L9

On Wed, Mar 23, 2016 at 12:32 PM, Scott Chamberlain <
notifications@github.com> wrote:

> Also added functionality to endpoint to support sealifebase queries
>
> Where is this change?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/rfishbase/pull/96#issuecomment-200079070>
>



-- 
Phil

**Comment by Philipp-Neubauer** [comment]
and

https://github.com/Philipp-Neubauer/rfishbase/blob/cherrypick/R/00-endpoint.R#L38

for the second; added a query arg to the endpoint function to allow for
custom queries.

Sorry for the confusion, didn't realise that additional commits to the same
branch are automatically added to a pull request, hence the PS messages.

On Wed, Mar 23, 2016 at 12:34 PM, Philipp Neubauer <neubauer.phil@gmail.com>
wrote:

>
> https://github.com/Philipp-Neubauer/rfishbase/blob/cherrypick/R/00-endpoint.R#L9
>
> On Wed, Mar 23, 2016 at 12:32 PM, Scott Chamberlain <
> notifications@github.com> wrote:
>
>> Also added functionality to endpoint to support sealifebase queries
>>
>> Where is this change?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ropensci/rfishbase/pull/96#issuecomment-200079070>
>>
>
>
>
> --
> Phil
>



-- 
Phil

**Comment by sckott** [comment]
Sorry to ask for something else, but can you add some tests for this new code, just the new functionality that the changes entail. I'm just not sure of how endpoint is supposed to behave with the changes, so it'd be nice to see a few tests

**Comment by Philipp-Neubauer** [comment]
added a raft of tests; some are in species - they are fairly general endpoint tests I suppose, but they seemed consistent with other tests for the species table as they involve the species_list in the query. I put the test for the custom query in the endpoint test. Doc is updated to reflect changes, in hopes that it passes the CI check...

**Comment by sckott** [comment]
LGTM

**Pull request merged**
